baseurl = "https://www.misp-project.org/"
title = "MISP Open Source Threat Intelligence Platform & Open Standards For Threat Information Sharing"
theme = "hugo-universal-theme"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# number of words of summarized post content (default 70)
summaryLength = 20

# Define the number of posts per page
paginate = 20

disablePathToLower = "True"

[outputFormats]
[outputFormats.RSS]
mediatype= "application/rss"
baseName= "feed"

[menu]


# Main menu
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "Features"
    identifier = "menu.features"
    url        = "/features/"
    weight     = 2

[[menu.main]]
    name       = "Data Models"
    identifier = "menu.datamodels"
    url        = "/img/misp-standard.png"
    weight     = 3

[[menu.main]]
    name       = "Data Models"
    url        = "/datamodels/"
    identifier = "section.dm"
    weight     = 1
    parent     = "menu.datamodels"
    post       = 1

[[menu.main]]
    name       = "MISP core format"
    url        = "/datamodels/#misp-core-format"
    weight     = 2
    parent     = "menu.datamodels"
    post       = 1

[[menu.main]]
    name       = "MISP taxonomies"
    url        = "/datamodels/#misp-taxonomies"
    weight     = 3
    parent     = "menu.datamodels"
    post       = 1

[[menu.main]]
    name       = "MISP Galaxy"
    url        = "/datamodels/#misp-galaxy"
    weight     = 4
    parent     = "menu.datamodels"
    post       = 1

[[menu.main]]
    name       = "MISP Objects"
    url        = "/datamodels/#misp-objects"
    weight     = 5
    parent     = "menu.datamodels"
    post       = 1

[[menu.main]]
    name       = "Default feeds"
    url        = "/feeds/"
    weight     = 6
    parent     = "menu.datamodels"
    post       = 1

[[menu.main]]
    name       = "Download"
    identifier = "menu.download"
    url        = "/download/"
    weight     = 55

[[menu.main]]
    name       = "Communities"
    identifier = "menu.communities"
    url        = "/communities/"
    weight     = 50

[[menu.main]]
    name       = "Events"
    identifier = "menu.events"
    url        = "/events/"
    weight     = 60

[[menu.main]]
    name       = "Events"
    url        = "/events/"
    weight     = 1
    parent     = "menu.events"

[[menu.main]]
    name       = "Webinars"
    url        = "/events-webinar/"
    weight     = 2
    parent     = "menu.events"

[[menu.main]]
    name       = "Hackathon"
    url        = "/hackathon/"
    weight     = 3
    parent     = "menu.events"

[[menu.main]]
    name       = "MISP Summit"
    url        = "/misp-summit/"
    weight     = 4
    parent     = "menu.events"


[[menu.main]]
    name       = "News"
    identifier = "menu.blog"
    url        = "/blog/"
    weight     = 80


[[menu.main]]
    identifier = "menu.contact"
    name       = "Contact"
    url        = "/img/menu-contact.png"
    weight     = 90

[[menu.main]]
    identifier = "section.contact"
    name       = "Reaching us"
    parent     = "menu.contact"
    weight     = 1
    post       = 1

[[menu.main]]
    name       = "Contact Us"
    url        = "/support/"
    weight     = 1
    parent     = "section.contact"

[[menu.main]]
    name       = "Press inquiries"
    url        = "/press/"
    weight     = 2
    parent     = "section.contact"


[[menu.main]]
    name       = "Professional Services"
    url        = "/professional-services/"
    weight     = 2
    parent     = "section.contact"
    post       = 1

[[menu.main]]
    name       = "Security Matters"
    url        = "/security/"
    weight     = 2
    parent     = "section.contact"
    post       = 1



[[menu.main]]
    identifier = "section.who"
    name       = "Who are we?"
    parent     = "menu.contact"
    weight     = 1
    post       = 2

[[menu.main]]
    name       = "The core team"
    url        = "/who/"
    weight     = 3
    parent     = "section.who"

[[menu.main]]
    name       = "Contributors"
    url        = "/contributors/"
    weight     = 4
    parent     = "section.who"

[[menu.main]]
    name       = "Governance"
    url        = "/governance/"
    weight     = 6
    parent     = "section.who"



[[menu.main]]
    identifier = "menu.documentation"
    name       = "Documentation"
    url        = "/img/menu-book.png"
    weight     = 40


[[menu.main]]
    name       = "Documentation"
    identifier = "section.documentation"
    parent     = "menu.documentation"
    weight     = 1
    post       = 1

[[menu.main]]
    name       = "Documentation"
    url        = "/documentation/"
    weight     = 1
    parent     = "section.documentation"
    post       = 1

[[menu.main]]
    name       = "OpenAPI"
    url        = "/documentation/openapi.html"
    weight     = 2
    parent     = "section.documentation"

[[menu.main]]
    name       = "Tools"
    url        = "/tools/"
    weight     = 3
    parent     = "section.documentation"

[[menu.main]]
    name       = "Support"
    url        = "/support/"
    weight     = 4
    parent     = "section.documentation"

[[menu.main]]
    name       = "Contributing"
    identifier = "section.contributing"
    url        = "/contributing/"
    weight     = 5
    parent     = "section.documentation"

[[menu.main]]
    name       = "Research projects"
    url        = "/research-projects/"
    weight     = 6
    parent     = "section.documentation"

[[menu.main]]
    name       = "Legal"    
    identifier = "section.legal"
    url        = ""
    weight     = 5
    parent     = "menu.documentation"
    post       = 2

[[menu.main]]
    name       = "License"
    url        = "/license/"
    weight     = 1
    parent     = "section.legal"

[[menu.main]]
    name       = "Legal and policy"
    url        = "/compliance/"
    weight     = 11
    parent     = "section.legal"

[[menu.main]]
    name       = "GDPR"
    url        = "/compliance/GDPR"
    weight     = 12
    parent     = "section.legal"

[[menu.main]]
    name       = "ISO/IEC 27010:2015"
    url        = "/compliance/ISO-IEC-27010/"
    weight     = 13
    parent     = "section.legal"

[[menu.main]]
    name       = "NISD"
    url        = "/compliance/NISD"
    weight     = 14
    parent     = "section.legal"




# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Book"
    url = "/documentation"
    pre = "<i class='fas fa-2x fa-book'></i>"

[[menu.topbar]]
    weight = 2
    name = "GitHub"
    url = "https://github.com/MISP/"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 3
    name = "Gitter"
    url = "https://gitter.im/MISP/MISP"
    pre = "<i class='fab fa-2x fa-gitter'></i>"

[[menu.topbar]]
    weight = 4
    name = "Twitter"
    url = "https://twitter.com/MISPProject"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 5
    name = "Email"
    url = "mailto:info@misp-project.org"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[[menu.topbar]]
    weight = 6
    name = "RSS Feed"
    url = "/feed.xml"
    pre = "<i class='fas fa-2x fa-rss'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "MISP"
    defaultKeywords = ["MISP", "CTI", "malware", "threat", "cyber", "intelligence", "information exchange", "sharing", "open source", "MISP threat sharing", "Malware Information Sharing Platform", "Threat Intelligence Platform", "TIP", "information sharing", "threatintel"]
    mainSections = ["blog"]
    defaultDescription = "MISP Threat Intelligence & Sharing "

    # Social media
    #facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "MISPProject" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = false
    googleMapsApiKey = ""

    #latitude = "-12.043333"
    #longitude = "-77.028333"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
    formspree_action = "https://formspree.io/sample/of/endpoint"
    contact_form_ajax = false

    # Formspree form supports Google reCAPTCHA Key (type v2).
    # If you use this feature, you should enable reCAPTCHA feature in the Formspree dashboard.
    #
    # By default, Formspree use a redirect page for recaptcha widget.
    # If you use a recaptcha widget in your contact page, you should do next steps.
    # (if you don't want, skip these steps)
    #
    #   1. register your site on Google recaptcha admin page: https://www.google.com/recaptcha/admin
    #   2. select reCAPTCHA v2 and checkbox widget type.
    #   3. remember site key and secret key.
    #   4. enter secret key into "Custom reCAPTCHA Key" field in your Formspree form setting page.
    #   5. change `enableRecaptchaInContactForm` is to true
    #   6. enter site key into `googleRecaptchaKey` to enable a recaptcha widget in your page.
    #
    enableRecaptchaInContactForm = false
    googleRecaptchaKey = "site_key_for_google_recaptcha"

    about_us = '<img class="img-responsive" src="/img/cef-white.png"><br/><a href="https://www.misp-standard.org/"><img class="img-responsive" src="/img/misp-standard-dark.png"></a>'
    copyright = 'Â© MISP project. Software released under <a href="/license/">approved open source licenses</a> and content of this website released as CC BY-SA 3.0.'

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    disabled_logo = false
    logo_text = "MISP Threat Sharing"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    contact_url = "/support"
    address = """
      """

[permalinks]
    blog = "/:year/:month/:day/:filename.html"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carouselCustomers]
    items = 6
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselTestimonals]
    items = 4
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = true
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.download]
    enable = true
    icon = "fas fa-download"
    title = "Want to test and evaluate MISP?"
    subtitle = ""
    link_url = "/download"
    link_text = "Download now"


[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Initiatives"
    subtitle = "The MISP Threat Sharing project consists of multiple initiatives, from software to facilitate threat analysis and sharing to freely usable structured Cyber Threat Information and Taxonomies."

[params.see_more]
    enable = true
    icon = "far fa-file-alt"
    title = "Do you want to join a community?"
    subtitle = "MISP is an open source software and it is also a large community of MISP users creating, maintaining and operating communities of users or organizations sharing information about threats or cyber security indicators worldwide."
    link_url = "/communities"
    link_text = "Find communities"

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = "In addition to the [news](/blog/) stories below, check out the [press](/press), [events](/events), [hackathon](hackathon), [MISP Summit](misp-summit) pages and full [news archive](/blog)."
    hide_summary = false

[params.footer.recent_posts]
    enable = true

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
